name             'mm_common'
description      'Recipes for configuring common server aspects within a Meteor Multiverse stack'
maintainer       'James M. Greene'
maintainer_email 'james.m.greene@gmail.com'
license          'MIT'
version          '1.0.0'
