###
# This is the place to override {thisCookbookName}'s default attributes.
#
# Do not edit THIS file directly. Instead, create
# "{thisCookbookName}/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

normal['mm']['layers']['nginx']['foo'] = 'xyz'
